Update installer
dusk-network/itn-installer pull request #22
Opened 2024-02-12 22:56 UTC by HDauven

Resolves #21

2024-02-14 18:03 UTC, herr-seppia requested changes

2024-02-14 18:03 UTC, herr-seppia commented on services/rusk.service
>  ExecStartPre=!/bin/bash -c '/opt/dusk/bin/check_consensuskeys.sh'
You should update check_consensus_keys.sh to check the proper path

2024-02-14 18:09 UTC, HDauven commented on conf/wallet.toml
Are you sure? I think setting this as the default for the droplet wallet makes sense, no?

2024-02-15 08:55 UTC, HDauven commented on itn-installer.sh
> +unzip -d /opt/dusk/.rusk/ -o /opt/dusk/installer/rusk-vd-keys.zip
-d doesn't exist AFAIK, used dusk:dusk instead

2024-02-15 13:42 UTC, HDauven commented on services/rusk.service
> -ExecStartPre=!/bin/bash -c 'chown -R dusk $RUSK_PROFILE_PATH'
@herr-seppia shame call out

2024-02-15 14:29 UTC, herr-seppia approved these changes

2024-02-15 14:29 UTC, merged